const qs=(s,p=document)=>p.querySelector(s), qsa=(s,p=document)=>[...p.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches, coarse=matchMedia('(pointer: coarse)').matches;
const loader=qs('.loader'), counter=qs('.loader b'), bar=qs('.loader-bar i');
if(!reduced){let n=0;const t=setInterval(()=>{n=Math.min(100,n+Math.ceil((100-n)*.11));counter.textContent=String(n).padStart(3,'0');bar.style.width=n+'%';if(n===100){clearInterval(t);setTimeout(()=>loader.classList.add('done'),180)}},35)}else loader.remove();
if(!coarse){const c=qs('.cursor'),label=qs('.cursor span');let x=innerWidth/2,y=innerHeight/2,cx=x,cy=y;addEventListener('pointermove',e=>{x=e.clientX;y=e.clientY});(function loop(){cx+=(x-cx)*.16;cy+=(y-cy)*.16;c.style.transform=`translate(${cx-32}px,${cy-32}px)`;requestAnimationFrame(loop)})();qsa('[data-cursor]').forEach(el=>{el.addEventListener('mouseenter',()=>{label.textContent=el.dataset.cursor;c.classList.add('active')});el.addEventListener('mouseleave',()=>{label.textContent='VIEW';c.classList.remove('active')})})}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});qsa('.reveal').forEach(e=>io.observe(e));
qsa('.magnetic').forEach(el=>{if(coarse)return;el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.15}px,${(e.clientY-r.top-r.height/2)*.15}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
const menu=qs('.menu'),panel=qs('.mobile-panel');menu.addEventListener('click',()=>{const open=panel.classList.toggle('open');menu.setAttribute('aria-expanded',open);panel.setAttribute('aria-hidden',!open)});qsa('.mobile-panel a').forEach(a=>a.onclick=()=>{panel.classList.remove('open');menu.setAttribute('aria-expanded','false')});
const data={
resistojet:{index:'01',kicker:'Propulsion / CubeSat research',title:'Resistojet Thruster Upgrade',summary:'Led analysis for a warm-gas upgrade to an R134a cold-gas propulsion system. Connected thermal energy addition to exhaust velocity, modeled internal convection and cylindrical conduction, and scoped a nichrome heater implementation for future vacuum testing.',stats:[['35.64 W','required heat'],['380–385 °C','surface target'],['100 m/s','velocity goal']],tags:['R134a','Heat transfer','Python','Arduino','Vacuum test','AIAA']},
coldplate:{index:'02',kicker:'Thermal design / Additive manufacturing',title:'Cold Plate Development',summary:'Technical and commercial engineering work around copper additive-manufactured cold plates: architecture comparison, design iteration, thermal reasoning, manufacturing constraints, and translating technical detail into useful customer-facing decisions.',stats:[['Cu AM','manufacturing'],['CFD','validation path'],['AI','workflow support']],tags:['Cold plate','Copper AM','Thermal','CAD','Presales','Automation']},
turbofan:{index:'03',kicker:'Propulsion / Computational modeling',title:'Turbofan Cycle Analysis',summary:'Built performance models across compressor pressure ratio and bypass ratio sweeps, comparing thrust, specific thrust, fuel flow, and TSFC across multiple flight conditions and operating limits.',stats:[['1→15','pressure ratio'],['M 2.5','design case'],['10 km','flight case']],tags:['Turbofan','MATLAB','Python','TSFC','Cycle analysis']},
testing:{index:'04',kicker:'Experimental aerospace / Data reduction',title:'Aerospace Test Analysis',summary:'Processed and interpreted transient and steady test data across shock tubes, wind tunnels, gas turbines, modal vibration studies, and vacuum-chamber propulsion work—always with explicit attention to sensor assumptions and data-quality limits.',stats:[['16.7 Hz','modal range'],['50.7 N','SR-30 average'],['Re 200k/500k','wind tunnel']],tags:['Experiment','Sensors','Python','Uncertainty','Aerodynamics','Structures']}
};
const modal=qs('.project-modal');function openProject(key){const d=data[key];qs('.modal-index').textContent=`PROJECT ${d.index}`;qs('.modal-kicker').textContent=d.kicker;qs('.project-modal h2').textContent=d.title;qs('.modal-summary').textContent=d.summary;qs('.modal-stats').innerHTML=d.stats.map(s=>`<div><strong>${s[0]}</strong><span>${s[1]}</span></div>`).join('');qs('.modal-tags').innerHTML=d.tags.map(t=>`<i>${t}</i>`).join('');modal.showModal()}qsa('.project').forEach(p=>{p.onclick=()=>openProject(p.dataset.project);p.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')openProject(p.dataset.project)}});qs('.modal-close').onclick=()=>modal.close();modal.onclick=e=>{if(e.target===modal)modal.close()};
const counts=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,target=parseFloat(el.dataset.count),dec=String(target).includes('.')?2:0,start=performance.now();function tick(now){const p=Math.min(1,(now-start)/1200),v=target*(1-Math.pow(1-p,3));el.textContent=v.toFixed(dec);if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);counts.unobserve(el)}),{threshold:.7});qsa('[data-count]').forEach(e=>counts.observe(e));
